ADDED Infinite test run workflow FIXED ARTIFACT_ID > REPORT_ID

diff --git a/.github/workflows/inf_test_run.yml b/.github/workflows/inf_test_run.yml
--- a/.github/workflows/inf_test_run.yml
+++ b/.github/workflows/inf_test_run.yml
@@ -1,27 +1,15 @@
-name: Autotests
+name: Infinite Test Runner
 
 on:
-  workflow_dispatch:
-    inputs:
-      deployment_target:
-        description: Choose target
-        required: true
-        default: smoke_tests
-        type: choice
-        options:
-          - smoke_tests
-          - regression_tests
-          - pb1 smoke_tests
-          - pb1 regression_tests
-          - test700 smoke_tests
-          - test700 regression_tests
-          - conftest
+  push:
+    branches:
+      - main
 
 permissions:
   contents: read
   pages: write
   id-token: write
-  
+
 jobs:
   download-history:
     runs-on: ubuntu-latest
@@ -70,9 +58,8 @@ jobs:
   test:
     runs-on: ubuntu-latest
     # needs: download-history
-
     steps:
-      - name: Checkout repository
+      - name: Checkout code
         uses: actions/checkout@v4
       - name: setup Python
         uses: actions/setup-python@v4
@@ -84,34 +71,21 @@ jobs:
         run: pip install -r requirements.txt
       - name: Download all workflow run artifacts
         uses: actions/download-artifact@v4
-      - name: conftest
-        if: "github.event.inputs.deployment_target == 'conftest'"
-        run: pytest -m new --alluredir=results
+      - name: Run tests infinitely
+        run: |
+          while :; do
+            echo "### Starting test iteration ###" >> test.log
+            npm test >> test.log 2>&1 || echo "Tests failed, but continuing..." >> test.log
+            sleep 10  # Пауза между запусками
+          done
         continue-on-error: true
-      - name: smoke_tests
-        if: "github.event.inputs.deployment_target == 'smoke_tests'"
-        run: pytest -m smoke --alluredir=results
-        continue-on-error: true
-      - name: regression_tests
-        if: "github.event.inputs.deployment_target == 'regression_tests'"
-        run: pytest -m regression --alluredir=results
-        continue-on-error: true
-      - name: pb1 smoke_tests
-        if: "github.event.inputs.deployment_target == 'pb1 smoke_tests'"
-        run: pytest -m smoke --stage https://pm.ru/user/switch_platform/?platform=2 --alluredir=results
-        continue-on-error: true
-      - name: pb1 regression_tests
-        if: "github.event.inputs.deployment_target == 'pb1 regression_tests'"
-        run: pytest -m regression --stage https://pm.ru/user/switch_platform/?platform=2 --alluredir=results
-        continue-on-error: true
-      - name: test700 smoke_tests
-        if: "github.event.inputs.deployment_target == 'test700 smoke_tests'"
-        run: pytest -m smoke --stage http://m.testpm.ru:700/ --alluredir=results
-        continue-on-error: true
-      - name: test700 regression_tests
-        if: "github.event.inputs.deployment_target == 'test700 regression_tests'"
-        run: pytest -m regression --stage http://m.testpm.ru:700/ --alluredir=results
-        continue-on-error: true
+      - name: Upload test logs
+        if: always()  # Загружает логи даже при ошибке
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-logs
+          path: test.log
+          retention-days: 1
       - name: Store allure results
         uses: actions/upload-artifact@v4
         with:
@@ -120,7 +94,7 @@ jobs:
             results
           overwrite: true
           retention-days: 1
-        
+
   generate-report:
     runs-on: ubuntu-latest
     needs: test
@@ -141,7 +115,7 @@ jobs:
           path:
             _site
           retention-days: 1
-          
+
   publish-report:
     runs-on: ubuntu-latest
     needs: generate-report
@@ -154,4 +128,3 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4.0.5
-        
